// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGEwMMt_jq-GPIVO-MTrVgaPoDgRiNUWs',
    appId: '1:95583806226:web:6c0bda1abf5d87e86ec9cb',
    messagingSenderId: '95583806226',
    projectId: 'qconnect-5e16e',
    authDomain: 'qconnect-5e16e.firebaseapp.com',
    storageBucket: 'qconnect-5e16e.appspot.com',
    measurementId: 'G-GYR765F46W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPE18-FRwv4EV2JJw6j_-EoBDj3ek-lQY',
    appId: '1:95583806226:android:5a7db5174560bbb96ec9cb',
    messagingSenderId: '95583806226',
    projectId: 'qconnect-5e16e',
    storageBucket: 'qconnect-5e16e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_QPH8_wKXw_pF-R5Tv2tfE0Qmg_w7Wh0',
    appId: '1:95583806226:ios:022bba97fbb7d5016ec9cb',
    messagingSenderId: '95583806226',
    projectId: 'qconnect-5e16e',
    storageBucket: 'qconnect-5e16e.appspot.com',
    androidClientId: '95583806226-57afn0g0g1ejupeds4k493mkeju79eci.apps.googleusercontent.com',
    iosClientId: '95583806226-tfq19u4hm8vif57gf56pjfe3de7ea2te.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_QPH8_wKXw_pF-R5Tv2tfE0Qmg_w7Wh0',
    appId: '1:95583806226:ios:6f99d934fa1454466ec9cb',
    messagingSenderId: '95583806226',
    projectId: 'qconnect-5e16e',
    storageBucket: 'qconnect-5e16e.appspot.com',
    androidClientId: '95583806226-57afn0g0g1ejupeds4k493mkeju79eci.apps.googleusercontent.com',
    iosClientId: '95583806226-lncd098cjd70f1in09ia7iu9q7e4b8s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodui.RunnerTests',
  );
}
